var SSP=0,SIM=1,POS=2,EVO=3,alnBresults=[],alnAresults=[],homTypes=[0,1,2],alnAF=[],alnBF=[],padChars=20,charWidth,colDistA,colDistB,homType=2,sparklineDistanceType=!0,distances={},lock=[],def=[],G={},pack=function(a){return JSON.stringify(a)},unpack=function(a){return JSON.parse(a)},alertFallback=!1;if("undefined"===typeof console||"undefined"===typeof console.log)console={},console.log=alertFallback?function(a){alert(a)}:function(){};
$(function(){draganddrop("#alignment1");draganddrop("#alignment2");draganddrop("#newick")});function getHandleFileSelect(a){return function(b){console.log("HANDLING FILE");var b=b.originalEvent||b,d=b.target.files[0];console.log(b);getFile(d,a)}}function getFile(a,b){console.log("Attempting to get "+a);var d=new FileReader;d.onload=function(a){console.log(a);b.val(a.target.result)};d.readAsText(a)}
function draganddrop(a){var b=$(a);b.bind({dragover:function(){$(this).addClass("hover");return!1},dragend:function(){$(this).removeClass("hover");return!1},drop:function(a){a=a||window.event;a.preventDefault();a=a.originalEvent||a;console.log(a);getFile((a.files||a.dataTransfer.files)[0],b);return!1}})}
function example(a){$.ajax(location.protocol+"//"+location.host+"/"+location.pathname.split("/").slice(0,-1).join("/")+"/examples/example"+a+"a.fa").done(function(a){$("#alignment1").val(a)});$.ajax(location.protocol+"//"+location.host+"/"+location.pathname.split("/").slice(0,-1).join("/")+"/examples/example"+a+"b.fa").done(function(a){$("#alignment2").val(a)});$.ajax(location.protocol+"//"+location.host+"/"+location.pathname.split("/").slice(0,-1).join("/")+"/examples/example"+a+".tre").done(function(a){$("#newick").val(a)})}
function supports_web_workers(){return!!window.Worker}var useWorkers=supports_web_workers(),START=new Date;function dateStamp(a){var b=new Date;console.log(b-START+" : "+a);START=b}function process(){$("#errorBox").css("display","none");$("#dialogtext").html("Calculation of homology sets");dialogBox.center();dialogBox.open();_.defer(process1)}
function process1(){console.log("process1");G.doEvo=0;try{alnA=parser($("#alignment1").val(),"alignment 1");alnB=parser($("#alignment2").val(),"alignment 2");"nucleotide"==G.sequenceType&&$("#distanceVisualizationType").html($("#nuc-distanceVisualizationType").html());$("#nuc-distanceVisualizationType").remove();$("#distanceVisualizationType").kendoDropDownList({autoBind:!0});$("#distanceVisualizationType").data("kendoDropDownList").toggle();$("#distanceVisualizationType").data("kendoDropDownList").toggle();
alnA.sort(nameSorter);alnB.sort(nameSorter);alnADensity=calcDensity(alnA);alnBDensity=calcDensity(alnB);var a=checkConsistency(alnA,alnB);G.sequenceNumber=a[0];G.origLengths=a[1];G.names=nameLookup(alnA,G.sequenceNumber);newick_string=$("#newick").val().replace(/\s/g,"")}catch(b){$("#errorBox").html("<b>ERROR: "+b+"</b>");$("#errorBox").fadeIn();dialogBox.close();return}alnAresults=[];alnBresults=[];alnAresults[0]=[];alnBresults[0]=[];var d=_.after(2,process2);_.defer(function(){doHomology(newick_string,
alnA,G.sequenceNumber,d)});_.defer(function(){doHomology(newick_string,alnB,G.sequenceNumber,d)})}
function doHomology(a,b,d,e){if(useWorkers){var f=new Worker("script/homologySets.js");f.onmessage=function(a){a=unpack(a.data);if("error"==a.type)throw"ERROR: "+a.msg;"status"!=a.type&&"success"==a.type&&(alnA===b?(alnA=a.ans,G.doEvo=a.doEvo,G.doEvo&&homTypes.push(3),console.log("doEvo? "+a.doEvo),homType=2+G.doEvo):alnB===b&&(alnB=a.ans),e())};f.postMessage(pack({tree:a,aln:b,seqNum:d,set:3}))}else performHomologyWork(a,b,d,3),b[0].labeledContent[EVO]&&(G.doEvo=1,homType=3),e()}
function process2(){_.defer(function(){$("#dialogtext").html("Calculation of distances")});console.log("PROCESS 2");distances.character=Array(3+G.doEvo);distances.alignment=Array(3+G.doEvo);distances.sequence=Array(3+G.doEvo);if(useWorkers){var a=[2,1,0];G.doEvo&&a.unshift(3);lock=_.map(a,function(){return!0});def=_.map(a,function(){return $.Deferred()});var b=function(a){if(!(0>a)){var b=new Worker("script/distances.js"),f=def[a];b.onmessage=function(b){b=unpack(b.data).distances;distances.character[a]=
b.character;distances.alignment[a]=b.alignment;distances.sequence[a]=b.sequence;console.log("WRITTEN "+a);f.resolve()};b.postMessage(pack({A:alnA,B:alnB,dist:a}));console.log("Sent one!")}};b(3);_.each(a,function(a){def[a].done(function(){lock[a]=!1;b(a-1)})});alnAF[0]=sequenceMaker(alnA,"alnA",padChars);alnBF[0]=sequenceMaker(alnB,"alnB",padChars);def[homType].done(function(){_.defer(process3)})}else distanceFs=calcDistances(alnA,alnB),_.each([0,1,2,3],function(a){var b=distanceFs[a]();distances.character[a]=
b.character;distances.alignment[a]=b.alignment;distances.sequence[a]=b.sequence}),alnAF[0]=sequenceMaker(alnA,"alnA",padChars),alnBF[0]=sequenceMaker(alnB,"alnB",padChars),_.defer(process3)}function updateCurrentHomType(){console.log("UPDATE HOM")}function process3(){G.visualize=$("#doviz:checked").val();$("#controlPanel").css("display","");$("#input").remove();$("#instructions").remove();_.defer(updateCurrentHomType);_.defer(vis);dateStamp("end process3()")}var prog=0,progress=function(){dateStamp(prog++)};
function vis(){console.log("VIS");if(G.visualize){progress();G.doEvo?($("#evol").removeAttr("disabled"),$("#evol").html("evol (recommended)"),$("#pos").html("pos"),$("#homologyType").val(homType)):$("#evol").remove();progress();$("#homologyType").kendoDropDownList({autoBind:!0});progress();$("#homologyType").data("kendoDropDownList").toggle();progress();$("#homologyType").data("kendoDropDownList").toggle();progress();$("#distanceVisualizationPanel").css("display","inline");progress();cssCache=[[],
[],[],[]];alnAF[1]=_.map(homTypes,function(a){return _.memoize(function(){return colouredCSSMaker(distances.character[a],alnA,"alnA")})});progress();alnBF[1]=_.map(homTypes,function(a){return _.memoize(function(){return colouredCSSMaker(distances.character[a],alnB,"alnB")})});progress();var a=alnAF[0];progress();var b=alnBF[0];progress();parseInt($("#distanceVisualizationType option:selected").val());progress();a=makeVisualiser(a,b,alnA,alnB);progress();$("body").append(a);progress();progress();sparklineDistanceType?
$("#distanceToggle").html("similarity"):$("#distanceToggle").html("distance");progress();applyCSS(alnAF[0],alnAF[1][homType]());progress();applyCSS(alnBF[0],alnBF[1][homType]());progress();progress();charWidth=getCharWidth();progress();progress();progress();$("#alnA_seqs").scrollLeft(250);progress();$("#alnB_seqs").scrollLeft(250);progress();progress();recalculateSparklines();progress();redisplaySparklines();progress();recalculateMinilines();progress()}_.defer(function(){dialogBox.close()});_.defer(bindings);
dateStamp("end vis()")}
function bindings(){var a=function(){$("#alnA_"+k+"_"+j).removeClass("centralChar");$("#alnB_"+k+"_"+j).removeClass("centralChar");k=l;j=central;$("#charDist").text(Math.round(1E3*distances.character[homType][l][central])/1E3);$("#alnA_"+l+"_"+central).addClass("centralChar");$("#alnB_"+l+"_"+central).addClass("centralChar")},b,d,e,f,g=getPositions(alnA),h=getPositions(alnB);b=g[0];d=g[1];e=h[0];f=h[1];var j="",l=0,k=l,n=cumulativeGaps(alnA),m=cumulativeGaps(alnB);alnA_seqs=$("#alnA_seqs");alnB_seqs=
$("#alnB_seqs");alnA_names=$("#alnA_names");alnB_names=$("#alnB_names");var q=function(){alnA_seqs.scrollLeft(b[l][central]*charWidth);alnB_seqs.scrollLeft(e[l][central]*charWidth);redisplaySparklines()};sparkLineClickA=function(b){central=b.sparklines[0].getCurrentRegionFields().offset;central-=n[l][central];a();q()};sparkLineClickB=function(b){central=b.sparklines[0].getCurrentRegionFields().offset;central-=m[l][central];a();q()};verticalClick=function(a){var b=$(this).position().top,b=a.pageY-
b;console.log("GOT CLICK "+b);var a=$(this).height(),d=$("#alnA_seqs")[0].scrollHeight,e=Math.max(0,b/a-a/d/2)*d;console.log("scrollTop "+b+" "+d+" "+a+" "+a/2+" "+e);$("#alnA_seqs").scrollTop(e)};$("#alnA_Y").on("click",verticalClick);$("#alnB_Y").on("click",verticalClick);$("#alnB_sparkline").bind("sparklineClick",sparkLineClickB);$("#alnA_sparkline").bind("sparklineClick",sparkLineClickA);alnA_seqs.bind("click",function(b){l=$(b.target).closest("div").index();central=d[l][$(b.target).closest("span").index()-
padChars];a()});alnB_seqs.bind("click",function(b){l=$(b.target).closest("div").index();central=f[l][$(b.target).closest("span").index()-padChars];a()});$("#distanceToggle").click(function(){console.log("CLICK");(sparklineDistanceType=!sparklineDistanceType)?$(this).html("similarity"):$(this).html("distance");doRedisplaySparklines()});scrollA=_.debounce(function(){central=d[l][Math.round(alnA_seqs.scrollLeft()/charWidth)];a();alnB_seqs.off("scroll");alnB_seqs.scrollLeft(e[l][central]*charWidth);alnB_seqs.scrollTop(alnA_seqs.scrollTop());
alnA_names.scrollTop(alnA_seqs.scrollTop());alnB_names.scrollTop(alnA_seqs.scrollTop());redisplaySparklines();_.defer(function(){alnB_seqs.on("scroll",scrollB)})},100);scrollB=_.debounce(function(){central=f[l][Math.round(alnB_seqs.scrollLeft()/charWidth)];a();alnA_seqs.off("scroll");alnA_seqs.scrollLeft(b[l][central]*charWidth);alnA_seqs.scrollTop(alnB_seqs.scrollTop());alnA_names.scrollTop(alnB_seqs.scrollTop());alnB_names.scrollTop(alnB_seqs.scrollTop());redisplaySparklines();_.defer(function(){alnA_seqs.on("scroll",
scrollA)})},100);alnA_seqs.on("scroll",scrollA);alnB_seqs.on("scroll",scrollB);progress();g=function(){$("#distanceVisualizationType option:selected").each(function(){var a=$(this).val();$("#seqColour").attr("href","css/"+a+".css")})};g();$("#distanceVisualizationType").change(g);progress();$("#homologyType").change(function(){homType=parseInt($(this).val());var a=function(){var a=Math.round(1E6*distances.alignment[homType])/1E6;$("#alnDist").text(a);parseInt($("#distanceVisualizationType option:selected").val());
G.visualize&&(applyCSS(alnAF[0],alnAF[1][homType]()),applyCSS(alnBF[0],alnBF[1][homType]()),recalculateSparklines(),redisplaySparklines(),recalculateMinilines());G.charDists&&(a=makeCharDist(distances,homType,alnA),$("#chardists").replaceWith(a))};useWorkers&&"resolved"!=def[homType].state()?($("#dialogtext").html("Calculating distances..."),dialogBox.open(),def[homType].done(function(){console.log(distances.character);dialogBox.close();a()})):a()});g=makeOutput(distances,homType,alnA);$("body").append(g[0]);
$("#showCharDists").click(function(){var a=window.open("","charDists","height=400,width=400");a.document.write("<html><head>");a.document.write("</head><body><pre>");a.document.write(makeRawCharDist(distances,homType,alnA).join("\n"));a.document.write("</pre></body></html>");a.document.close()});$("#showSeqDists").click(function(){var a=window.open("","seqdists","height=600,width=400"),b=makeOutput(distances,homType,alnA);a.document.write("<html><head></head><body>"+$("<div/>").append(b[1]).html()+
"</body></html>");a.document.close()});g=function(){var a=$(window).height(),b=$("#visualiser").offset().top,b=b+$("#visualiser").outerHeight(!0),b=b-alnA_seqs.outerHeight(!0),b=b-alnB_seqs.outerHeight(!0),b=b+$("#output table").outerHeight(!0),a=(a-b)/2;alnA_seqs.css("height",a);alnA_names.css("height",a);alnB_seqs.css("height",a);alnB_names.css("height",a);$("#alnA_Y").css("height",a);$("#alnB_Y").css("height",a);redisplaySparklines()};g();$(window).resize(g);$("#consensus").on("click",function(){var a=
window.open("","consensus","height=400,width=400");a.document.write("<html><head>");a.document.write("</head><body><pre>");for(var b=0;b<alnA.length;b++){a.document.write(">"+alnA[b].name+"\n");for(var d=[],e=0;e<alnA[b].content.length;e++)0==colDistA[e]&&d.push(alnA[b].content[e]);a.document.write(d.join("")+"\n")}a.document.write("</pre></body></html>")});dateStamp("end bindings()")}
function cumulativeGaps(a){for(var b=[],d=0;d<a.length;d++){b[d]=[];b[d][0]="-"==a[d].content[0]?1:0;for(var e=1;e<a[d].content.length;e++)b[d][e]="-"==a[d].content[e]?b[d][e-1]+1:b[d][e-1]}return b}function recalculateSparklines(){colDistA=makeRawColumnDist(distances,homType,alnA);colDistB=makeRawColumnDist(distances,homType,alnB)}redisplaySparklines=_.throttle(doRedisplaySparklines,1E3);
function doRedisplaySparklines(){console.log("distance "+sparklineDistanceType);applyColumnDist(colDistA,alnADensity,$("#alnA_seqs"),$("#alnA_sparkline"),$("#alnA_seqs").width(),sparklineDistanceType);console.log("foo");applyColumnDist(colDistB,alnBDensity,$("#alnB_seqs"),$("#alnB_sparkline"),$("#alnB_seqs").width(),sparklineDistanceType);console.log("foo");var a=visibleRange($("#alnA_seqs"),alnA[0].content.length,alnA.length);console.log(a);var b=$("#alnA_Y"),d=$("#alnB_Y");b.empty();d.empty();for(var e=
0;e<distances.sequence[homType].length;e++){var f=100/distances.sequence[homType].length+"%";e>=a[3]&&e<=a[5]?(b.append($("<div class='bar-selected'/>").css("width",100*distances.sequence[homType][e]+"%").css("height",f)),d.append($("<div class='bar-selected'/>").css("width",100*distances.sequence[homType][e]+"%").css("height",f))):(b.append($("<div class='bar'/>").css("width",100*distances.sequence[homType][e]+"%").css("height",f)),d.append($("<div class='bar'/>").css("width",100*distances.sequence[homType][e]+
"%").css("height",f)))}}function recalculateMinilines(){var a=new Date;$("div#visualiser").find("div.miniline").each(function(a,d){var e=d.id.replace("miniline_",""),f=$(d);f.css("width","30%");f.html("<img src='png/"+Math.floor(100*distances.sequence[homType][e])+".png' title='"+distances.sequence[homType][e]+"' height='10px' style='max-width:100%'/>")});console.log(new Date-a)}
function calcDensity(a){for(var b=[],d=0;d<a.length;d++)for(var e=0;e<a[d].content.length;e++)"-"!=a[d].content[e]&&(b[e]||(b[e]=0),b[e]++);for(d=0;d<b.length;d++)b[d]/=a.length;return b};SSP=0;SIM=1;POS=2;EVO=3;try{importScripts("http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.3.3/underscore-min.js")}catch(e$$15){}onmessage=function(a){a=JSON.parse(a.data);dist=calcDistances(a.A,a.B);postMessage(JSON.stringify({type:"success",distances:dist[a.dist]()}))};function dssp(a,b,d,e){return d==e&&0<d?[a,b+1]:0<d&&0<e?[a+2,b+2]:0<d||0<e?[a+1,b+1]:[a,b]}function dseq(a,b,d,e){0>d&&(d=0);0>e&&(e=0);return dgen(a,b,d,e)}function dgen(a,b,d,e){return d!=e?[a+1,b+1]:[a,b+1]}
var dpos=dgen,devol=dgen;
function quickDistNew(a,b,d){var e=[],f=[],g=0,h=0,j,l=2;switch(d){case 0:j=dssp;break;case 1:j=dseq;break;case 2:j=dpos;break;case 3:j=devol,l=3}for(d=0;d<a.length;d++){e[d]=[];for(var k=f[d]=0,n=0,m=0;k<a[d].content.length&&n<b[d].content.length;)if("-"==a[d].content[k])k++;else{if("-"!=b[d].content[n]){for(var q=0,p=0,r=0;r<a.length;r++)r!=d&&(p=j(q,p,a[r].labeledContent[l][k],b[r].labeledContent[l][n]),q=p[0],p=p[1]);f[d]+=q;h+=q;q=0==p?0:q/p;e[d].push(q);m+=p;k++}n++}g+=m;f[d]/=m}p={};p.character=
e;p.alignment=h/g;p.sequence=f;return p}function calcDistances(a,b){var d=[],e=a[0].labeledContent.length;d.push(_.memoize(function(){return quickDistNew(a,b,0)}));for(var f=1;f<e;f++){var g=_.bind(quickDistNew,{},a,b,f);d.push(_.memoize(g))}return d}function getIntersection(a,b){for(var d=0,e=0;e<a.length;e++)"-"!=a[e]&&"-"!=b[e]&&a[e]==b[e]&&d++;return d}function getUnion(a,b){for(var d=0,e=0;e<a.length;e++)"-"!=a[e]&&"-"!=b[e]?(d++,a[e]!=b[e]&&d++):("-"!=a[e]||"-"!=b[e])&&d++;return d};function Sequence(a,b){if(!(this instanceof Sequence))return new Sequence(a,b);this.name=a;this.content=b}var nextNodeID=0,nodeIDs={};function nodeID(a){return a.toString()+"---"}
function parser(a,b){var d=[],e,f,g=RegExp("(^>.+)(?:\n)(^[^>]+)","mg");G.sequenceType="nucleotide";for(var h=/[^ABCDEFGHIKLMNOPQRSTUVWYZXabcdefghiklmnopqrstuvwyzx*-]/,j=/[EFILOPQZefilopqz*]/,l,k=0;parsing=g.exec(a);){e=parsing[1].trim().replace(/^>/,"").replace(/\s/g,"_");f=parsing[2].trim().replace(/\n/g,"");var n=f.search(h);if(-1!=n)throw"Invalid character in sequence "+e+': "'+f[n]+'"';-1!=f.search(j)&&(G.sequenceType="amino acid");d[k]=new Sequence(e,f);if(l&&l!=d[k].content.length)throw"Sequences of differing lengths in "+
b;l=d[k].content.length;k++}return d}function labeller(a,b,d,e){for(var f=0;f<e;f++)a[f].labeledContent=[];d&&evoLabeller(a,b,e);for(f=0;f<e;f++){a[f].labeledContent[SSP]=[];a[f].labeledContent[SIM]=[];a[f].labeledContent[POS]=[];for(var g=b=0,h=0;h<a[f].content.length;h++)"-"!=a[f].content[h]?(g=++b,a[f].labeledContent[POS].push(g),d&&(a[f].labeledContent[EVO][h]=g)):(a[f].labeledContent[POS].push(-g),d&&(a[f].labeledContent[EVO][h]=-(1E4*a[f].labeledContent[EVO][h]+g)))}}
function nameLookup(a,b){names={};for(var d=0;d<b;d++)names[a[d].name]=d;return names}function evoLabeller(a,b,d){for(var e=nameLookup(a,d),f=0;f<d;f++)a[f].labeledContent[EVO]=[];for(var g=0;g<a[0].content.length;g++){gapMemory=[];for(f=0;f<d;f++)"-"==a[f].content[g]&&gapMemory.push(a[f].name);if(0<gapMemory.length){splits=b.splitsFor(gapMemory);for(f=0;f<gapMemory.length;f++)a[e[gapMemory[f]]].labeledContent[EVO][g]=splits[gapMemory[f]]}}}
function nameSorter(a,b){return void 0==a.name&&void 0!=b.name?1:void 0==b.name&&void 0!=a.name||a.name<b.name?-1:a.name>b.name?1:0};function checkConsistency(a,b){var d,e=[],f=[],g=[],h,j,l=[];if(!G.ignoreNamesFlag)for(var k=0;k<d;k++)if(a[k].name!=b[k].name)throw'Sequence identifiers are not consistent between alignments. Fix this issue or use "Ignore Names" if you are certain the sequences are in the same order in both alignments';if(a.length!=b.length)throw"Both alignments must contain the same number of sequences";d=a.length;for(k=0;k<d;k++){e[k]=a[k].content.replace(/-/g,"");f[k]=b[k].content.replace(/-/g,"");h=e[k].length;
j=f[k].length;if(h!=j)throw d=G.ignoreNamesFlag?k+1:'"'+a[k].name+'"',"Sequences "+d+" in each alignment are not mutually consistent due to different lengths";l[k]=h;g[k]=e[k]}return[d,l,g]};function sequenceMaker(a,b){var d=charPadding(padChars);$sequenceDiv=$("<div/>").attr("id",b+"_seqs").addClass("seqs");for(var e=0;e<G.sequenceNumber;e++){$colouredSeqDivs=$("<div/>").addClass("seq_"+e).append(d);for(var f=0,g=0;g<a[e].content.length;g++){var h=$("<span/>").text(a[e].content[g]).addClass(a[e].content[g].toUpperCase()).addClass("clickable");"-"!=a[e].content[g]&&(h.attr("id",b+"_"+e+"_"+f),f++);$colouredSeqDivs.append(h)}$sequenceDiv.append($colouredSeqDivs.append(d))}return $sequenceDiv}
function colouredCSSMaker(a,b){for(var d=[],e=[],f=0;f<G.sequenceNumber;f++){e[f]=[];for(var g=0,h=0;h<b[f].content.length;h++)"-"!=b[f].content[h]?($character=[Math.round(255*a[f][g]),Math.round(1E6*a[f][g])/1E6],g++):$character=null,e[f].push($character);d.push(e[f])}return d}
function applyCSS(a,b){var d=0;_.each($(a).children("div"),function(a){var f=0;_.each($(a).contents(".clickable"),function(a){if(b[d][f]){var e=$(a);_.chain(e.attr("class").split(" ")).filter(function(a){return"dist"==a.substring(0,4)}).each(function(a){e.removeClass(a)});e.addClass("dist"+b[d][f][0]);e.attr("title",b[d][f][1])}f++});d++});return a}
function makeVisualiser(a,b,d,e){var f=$("<div/>").attr("id","visualiser"),g=$("<div/>").attr("id","alnA_names").addClass("names"),h=$("<div/>").attr("id","alnB_names").addClass("names");for(i=0;i<G.sequenceNumber;i++)0==i%2?(g.append("<div class='row0'><div class='name' title='"+d[i].name+"'>"+d[i].name+"</div><div class='miniline' id='miniline_"+i+"'></div></div>"),h.append("<div class='row0'><div class='name' title='"+e[i].name+"'>"+e[i].name+"</div><div class='miniline' id='miniline_"+i+"'></div></div>")):
(g.append("<div class='row1'><div class='name' title='"+d[i].name+"'>"+d[i].name+"</div><div class='miniline' id='miniline_"+i+"'></div></div>"),h.append("<div class='row1'><div class='name' title='"+e[i].name+"'>"+e[i].name+"</div><div class='miniline' id='miniline_"+i+"'></div></div>"));g.append($("<div>&nbsp;</div>").css("height",scrollbarWidth()));h.append($("<div>&nbsp;</div>").css("height",scrollbarWidth()));$alnADistPlot=$("<div class='aln_y'/>").attr("id","alnA_Y");$alnBDistPlot=$("<div class='aln_y'/>").attr("id",
"alnB_Y");d=$("<div/>").append(g,$alnADistPlot,a).attr("id","alnA_scroll").addClass("scrollbox");b=$("<div/>").append(h,$alnBDistPlot,b).attr("id","alnB_scroll").addClass("scrollbox");h=$("<button class='k-button' id='distanceToggle' />");h.css("height","30px").css("font-size","14px").css("margin-top","7px").css("float","left");e=$("<span />").attr("id","alnA_sparkline").css("height","40px").css("width",a.width()).css("float","right").css("padding-top","5px");e=$("<div />").css("width","100%").css("overflow",
"hidden").css("display","block").append(h).append(e);h.html("distance");a=$("<span />").attr("id","alnB_sparkline").css("height","40px").css("width",a.width()).css("float","right").css("padding-top","5px");a=$("<div />").css("width","100%").css("overflow","hidden").css("display","block").append(a);f.append(d,e,b,a);return f}
function makeOutput(a,b,d){var e=$("<div/>").attr("id","output"),f=$("<table/>").attr("id","output"),g=Math.round(1E6*a.alignment[b])/1E6;if(G.visualize){var h=$("<table/>").css("display","inline").css("float","left").append($("<tr />"));h.append($("<td />").append("Total alignment distance:"));h.append($("<td />").attr("id","alnDist").css("width","8em").css("font-weight","bold").text(g));e.append(h);h=$("<table/>").css("display","inline").css("float","right").append($("<tr />"));h.append($("<td />").append("Focused character distance:"));
h.append($("<td />").attr("id","charDist").css("font-weight","bold").css("width","5em"));e.append(h)}var h=$("<tr/>"),g=$("<td />").attr("id","alnDist").text(g),j=$("<td />").append("Alignment distance");h.append(j);h.append(g);for(g=0;g<G.sequenceNumber;g++){var l=Math.round(1E6*a.sequence[b][g])/1E6,j=$("<tr/>"),k=$("<td/>").append("Distance for sequence "+d[g].name),l=$("<td/>").attr("id",d[g].name+"_dist").text(l);j.append(k);j.append(l);f.append(j)}f.append(h);return[e,f]}
function makeCharDist(a,b,d){for(var e=$("<div/>").attr("id","chardists"),f=[],g=0;g<G.sequenceNumber;g++){var h=[];h.push(d[g].name);for(var j=0;j<G.origLengths[g];j++)h.push(a.character[b][g][j]);f[g]=$("<p/>").attr("id","chardists_"+d[g].name).html(h.toString());e.append(f[g])}return e}function makeRawCharDist(a,b,d){for(var e=[],f=0;f<G.sequenceNumber;f++){var g=[];g.push(d[f].name);for(var h=0;h<G.origLengths[f];h++)g.push(a.character[b][f][h]);e.push(g)}return e}
function makeRawColumnDist(a,b,d){for(var e=[],f=0;f<d[0].content.length;f++)e[f]=0;for(var g=0;g<d.length;g++)for(var h=0,j=d[g].content,f=0;f<j.length;f++)"-"!=j[f]&&(e[f]+=a.character[b][g][h]/d.length,h++);return e}
function visibleRange(a,b,d){var e=a.scrollLeft(),f=a[0].scrollWidth,g=a.width(),h=b+2*padChars,j=Math.floor(e/f*h),j=j-padChars,e=Math.floor((e+g)/f*h),e=e-padChars;e>b&&(e=b);0>j&&(j=0);return d?(b=a.scrollTop(),f=a[0].scrollHeight,g=a.height(),a=Math.floor(b/f*d),d=Math.floor((b+g)/f*d),[j,Math.floor((j+e)/2),e,a,Math.floor((a+d)/2),d]):[j,Math.floor((j+e)/2),e]}
function applyColumnDist(a,b,d,e,f,g){for(var h=visibleRange(d,a.length),d=h[0],h=h[2],j=[],l=[],k=[],n=[],m=0;m<d;m++)j.push(a[m]),l.push(null),k.push(b[m]),n.push(null);j.push(a[d]);l.push(a[d]);k.push(b[d]);n.push(b[d]);for(m=d+1;m<h-1;m++)l.push(a[m]),j.push(null),n.push(b[m]),k.push(null);j.push(a[h-1]);l.push(a[h-1]);n.push(b[h-1]);k.push(b[h-1]);for(m=h;m<a.length;m++)j.push(a[m]),l.push(null),k.push(b[m]),n.push(null);e.css("width",f+"px");barWidth=Math.max(f/a.length,1);console.log("INVERT? "+
g);if(g)for(m=0;m<a.length;m++)null!=j[m]&&(j[m]=b[m]-j[m]),null!=l[m]&&(l[m]=b[m]-l[m]);e.sparkline(k,{width:f,chartRangeMax:1,chartRangeMin:0,height:"30px",lineColor:"#444444",fillColor:"#444444",disableTooltips:!0,disableHighlight:!0,spotColor:!1,minSpotColor:!1,maxSpotColor:!1});e.sparkline(n,{composite:!0,width:f,chartRangeMax:1,chartRangeMin:0,height:"30px",lineColor:"black",fillColor:"black",disableTooltips:!0,disableHighlight:!0,spotColor:!1,minSpotColor:!1,maxSpotColor:!1});e.sparkline(j,
{composite:!0,chartRangeMax:1,chartRangeMin:0,height:"30px",chartRangeMax:1,width:f,fillColor:"#6c8be9",lineColor:!1,disableTooltips:!0,disableHighlight:!0,spotColor:!1,minSpotColor:!1,maxSpotColor:!1});e.sparkline(l,{width:f,chartRangeMax:1,chartRangeMin:0,height:"30px",composite:!0,lineColor:!1,fillColor:"blue",disableTooltips:!0,disableHighlight:!0,spotColor:!1,minSpotColor:!1,maxSpotColor:!1})}
function getPositions(a){for(var b=[],d=[],e=0;e<G.sequenceNumber;e++){b[e]=[];d[e]=[];for(var f=0,g=0;g<a[e].content.length;g++)d[e][g]=f,b[e][f]=g,"-"!=a[e].content[g]&&f++}return[b,d]}function scanCentralChar(a){for(startingPoint=Math.round(a);void 0==characterAt[0][0][startingPoint];)startingPoint--;return characterAt[0][0][startingPoint]}
function charPadding(a){str='<span class="padding">&nbsp;</span>';if(!a)return"";for(var b=str,d=[str],e=1,f,g;e<a;){f=a-e;str=b;for(g=2;g<f;g*=2)str+=str;d.push(str);e+=g/2}return d.join("")}
function changeDistanceVisualization(a){if(a)for(b=0;b<G.sequenceNumber;b++)for(d=0;d<G.origLengths[b];d++)$("#alnA_"+b+"_"+d).css("background-color",a[b][d]),$("#alnB_"+b+"_"+d).css("background-color",a[b][d]);else for(var b=0;b<G.sequenceNumber;b++)for(var d=0;d<G.origLengths[b];d++)$("#alnA_"+b+"_"+d).css("background-color","")}
function getCharWidth(){var a,b=$("<div/>").addClass("seqs");b.append($("<span id='widthTest'>A</span>"));b.appendTo($("body"));a=parseInt($("#widthTest").css("padding-left"))+parseInt($("#widthTest").css("padding-right"))+$("#widthTest").width();b.remove();return a-1}
function scrollbarWidth(){var a=jQuery('<div style="width: 100%; height:200px;">test</div>'),b=jQuery('<div style="width:200px;height:150px; position: absolute; top: 0; left: 0; visibility: hidden; overflow:hidden;"></div>').append(a),d=a[0],a=b[0];jQuery("body").append(a);d=d.offsetWidth;b.css("overflow","scroll");a=a.clientWidth;b.remove();return d-a};SSP=0;SIM=1;POS=2;EVO=3;try{importScripts("newick_parser.js","sequence.js"),importScripts("http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.3.3/underscore-min.js")}catch(e$$17){}pack=function(a){return JSON.stringify(a)};unpack=function(a){return JSON.parse(a)};
onmessage=function(a){var a=unpack(a.data),b=a.tree,d=0,e=a.aln;try{e=performHomologyWork(b,e,a.seqNum),e[0].labeledContent[EVO]&&(d=1)}catch(f){f.message?(a=f.stack.replace(/^[^\(]+?[\n$]/gm,"").replace(/^\s+at\s+/gm,"").replace(/^Object.<anonymous>\s*\(/gm,"{anonymous}()@").split("\n"),postMessage(pack({type:"error",msg:f+"\n"+a}))):postMessage(pack({type:"error",msg:f}));return}postMessage(pack({type:"success",ans:e,doEvo:d}))};
function performHomologyWork(a,b,d){if(a){root=parseNewickString(a);treeNames=[];for(a=0;a<root.length;a++)treeNames.push(root[a].name);treeNames.sort();for(a=0;a<b.length;a++)if(treeNames[a]!=b[a].name)throw"Names differ in Newick tree and alignments";if(void 0!=treeNames[b.length])throw"There are more sequences in the Newick tree than in the alignments";doEvo=1;tree=makeTree(root)}else tree=null,doEvo=0;try{postMessage(pack({type:"status",msg:"1"}))}catch(e){}labeller(b,tree,doEvo,d);try{postMessage(pack({type:"status",
msg:"2"}))}catch(f){}return b}function resortNonOverlapping(a,b){var d;do{d=!1;for(var e=0;e<a[0].content.length-1;e++)if(areNonOverlapping(e,a,b)&&shouldBeFlipped(e,a,b)){for(d=0;d<b;d++){var f=a[d].content.substr(0,e).concat(a[d].content[e+1]).concat(a[d].content[e]).concat(a[d].content.substr(e+2));a[d].content=f}d=!0}}while(d);return a}function areNonOverlapping(a,b,d){for(var e=!0,f=0;f<d;f++)if("-"!=b[f][a]&&"-"!=b[f][a+1]){e=!1;break}return e}
function shouldBeFlipped(a,b,d){for(var e=!1,f=0;f<d;f++)if(!("-"==b[f][a]&&"-"==b[f][a+1])){e="-"==b[f][a+1];break}return e};try{importScripts("http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.3.3/underscore-min.js")}catch(e$$22){}function Node(){if(!(this instanceof Node))return new Node}Node.prototype.isRoot=function(){return"undefined"===typeof this.nodeparent};Node.prototype.isLeaf=function(){return"undefined"===typeof this.children||0==this.children.length};
Node.prototype.descendents=function(){try{var a;a=nodeList(this);var b=[];for(i=0;i<a.length;i++)a[i].isLeaf()&&b.push(a[i].name);return b}catch(d){throw"WTF!";}};Node.prototype.allSplits=function(){var a=this.descendents().sort(),b;b=nodeList(this);for(var d=[],e=0;e<b.length;e++)if(b[e].isLeaf())d.push([[b[e].name],_.without(a,b[e].name).sort()]);else{var f=b[e].descendents().sort();d.push([f,_.difference(a,f).sort()])}return d.sort()};
Node.prototype.splitsIDs=_.memoize(function(){var a=this.allSplits(),b={},d=0;_.each(a,function(a){b[a[0]]=d;b[a[1]]=d;d++});return b});Node.prototype.splitsFor=function(a){var b=this.splitsIDs();if(this.isRoot()){var d=splitsForRoot(this,a);_.chain(d).keys().each(function(a){d[a]=b[d[a].sort()]});return d}throw Error("Only call Node#splitsFor on the root!");};var c=0;
Node.prototype.findNodeWithNoneDesc=function(a){if(_.difference(this.descendents(),a).length==this.descendents().length)return this;if(this.children)for(var b=0;b<this.children.length;b++){var d=this.children[b].findNodeWithNoneDesc(a);if(d)return d}return null};
Node.prototype.downCopy=function(a){var b=nodeList(this),d=[];_.each(b,function(a){var b=new Node;a.name&&(b.name=a.name);b.id=a.id;d[b.id]=b});_.each(b,function(a){var b=d[a.id];a.nodeparent&&(b.nodeparent=d[a.nodeparent.id]);a.children&&(b.children=[],_.each(a.children,function(a){b.children.push(d[a.id])}))});d[this.id].nodeparent=a;a.children.push(d[this.id])};c=0;
Node.prototype.upCopy=function(a,b){var d=new Node;d.name=this.name;d.id=this.id;d.children=[];d.nodeparent=a;a.children.push(d);_.chain(this.children).filter(function(a){return a!==b}).each(function(a){a.downCopy(d)});this.nodeparent&&this.nodeparent.upCopy(d,this)};
Node.prototype.rootedCopy=function(){var a=new Node;a.name=this.nodeparent.name;a.id=this.nodeparent.id;a.children=[];_.each(this.nodeparent.children,function(b){b.downCopy(a)});this.nodeparent.nodeparent&&this.nodeparent.nodeparent.upCopy(a,this.nodeparent);return a};c=0;function splitsForRoot(a,b){var d=splitsForX(a,b);return _.reduce(d,function(a,b){a[b[0]]=b[1];return a},{})}
function splitsForX(a,b){var a=a.findNodeWithNoneDesc(b).rootedCopy(),d={},e={},f={},g=nodeList(a).reverse();_.each(g,function(a){var b;b=a.descendents();try{f[a.id]=b}catch(d){throw b;}});_.each(b,function(a){e[a]=1});for(var h=0;h<g.length;h++){var j=g[h];if(!j.children||0==j.children.length)1==e[j.name]&&(d[j.id]=1);else{var l=!0;_.each(j.children,function(a){d[a.id]||(l=!1)});l&&(_.each(j.children,function(a){delete d[a.id]}),d[j.id]=1)}}var k=[],n=_.filter(g,function(a){return d[a.id]}),m=!1;
_.each(n,function(b){var d=f[b.id];if(b.nodeparent===a){if(!m){m=!0;for(firstLevel=_.chain(n).filter(function(d){return d.nodeparent===a&&b!==d}).value();0<firstLevel.length;)d=d.concat(f[firstLevel.pop().id]);_.each(d,function(a){k.push([a,d])})}}else _.each(d,function(a){k.push([a,d])})});return k}Array.prototype.difference=function(a){return this.filter(function(b){return-1<a.indexOf(b)})};
Node.prototype.toString=function(){return this.children?(childstr="("+this.children.map(function(a){return a.toString()}).join()+")",this.isRoot()?childstr+";":childstr):this.name};
function parseNewickString(a){a=a.replace(/:[^),;]*/g,"");a=a.replace(/\)[^),;]*/g,")");if("("!=a[0])throw'Error: newick trees must start with an opening nodeparenthesis: "("';if(";"!=a[a.length-1])throw'Error: newick trees must end with a semi-colon: ";"';for(var b=unmatched=0;b<a.length;b++)"("==a[b]&&unmatched++,")"==a[b]&&unmatched--;if(0!=unmatched)throw"Error: newick tree contains different number of opening and closing nodeparentheses. ";temp={index:0,cursor:0,nodeparents:[]};a=basicParse(a);
delete temp;return a}function basicParse(a){if(null==b)var b=[];for(;";"!=a[temp.cursor];)switch(a[temp.cursor]){case "(":temp.cursor++;newNode(null,b,a);break;case ",":temp.cursor++;break;case ")":temp.nodeparents.pop();temp.cursor++;break;case ";":break;default:var d=a.substring(temp.cursor).match("^[0-9A-Za-z_|/\\.-]+"),d=d instanceof Array?d[0]:d;temp.cursor+=d.length;newNode(d,b,a)}return b}
function newNode(a,b,d){b[temp.index]=new Node;null==a?(b[temp.index].children=[],nodeLinker(b,d),temp.nodeparents.push(temp.index)):(b[temp.index].name=a,nodeLinker(b,d));temp.index++}function nodeLinker(a){temp.nodeparents.length&&(a[temp.index].nodeparent=temp.nodeparents[temp.nodeparents.length-1],a[a[temp.index].nodeparent].children.push(temp.index))}
function fixNode(a,b){b.children&&(b.children=b.children.map(function(b){return a[b]}));if(b.nodeparent||0==b.nodeparent)b.nodeparent=a[b.nodeparent];return b}function getRoot(a){for(var b=0;b<a.length;b++){var d=a[b];if(d.isRoot())return d}}function nodeList(a){var b=[];b.push(a);for(a=0;a<b.length;){if(b[a].children)for(var d=b[a].children,e=0;e<d.length;e++)b.push(d[e]);a+=1}return b}function enforceBi(a){stack=nodeList(a)[0];for(a=stack.length-1;0<=a;a--)doEnforceBi(stack[a])}
function doEnforceBi(a){if(a.children&&2!=a.children.length&&!(3==a.children.length&&a.isRoot()))if(1==a.children.length){par=a.nodeparent;a.children[0].nodeparent=par;for(var b=0;b<par.children.length;b++)par.children[b]==this&&(par.children[b]=a.children[0])}else for(;2<a.children.length;)b=new Node,b.children=a.children.slice(0,2),b.nodeparent=a,a.children[1]=b,a.children.shift()}
function unroot(a){if(3==a.children.length)return a;if(2!=a.children.length)throw Error("Tree is neither already rooted or bifurcating");a.children[0].isLeaf?(newroot=a.children[1],newchild=a.children[0]):(newroot=a.children[0],newchild=a.children[1]);newroot.children.push(newchild);newchild.nodeparent=newroot;newroot.nodeparent=void 0;return newroot}function makeTree(a){var b=getRoot(a.map(function(b){return fixNode(a,b)}));enforceBi(b);b=unroot(b);return numberNodes(b)}
function numberNodes(a){stack=nodeList(a);var b=0;_.each(stack,function(a){a.id=b;b++});return a};
