function checkConsistency(a,b){var d,e=[],f=[],g=[],h,j,l=[];if(!G.ignoreNamesFlag)for(var k=0;k<d;k++)if(a[k].name!=b[k].name)throw'Sequence identifiers are not consistent between alignments. Fix this issue or use "Ignore Names" if you are certain the sequences are in the same order in both alignments';if(a.length!=b.length)throw"Both alignments must contain the same number of sequences";d=a.length;for(k=0;k<d;k++){e[k]=a[k].content.replace(/-/g,"");f[k]=b[k].content.replace(/-/g,"");h=e[k].length;
j=f[k].length;if(h!=j)throw d=G.ignoreNamesFlag?k+1:'"'+a[k].name+'"',"Sequences "+d+" in each alignment are not mutually consistent due to different lengths";l[k]=h;g[k]=e[k]}return[d,l,g]};"function"!==typeof JSON.decycle&&(JSON.decycle=function(a){var b=[],d=[];return function f(a,h){var j,l,k;switch(typeof a){case "object":if(null===a||a instanceof Boolean||a instanceof Date||a instanceof Number||a instanceof RegExp||a instanceof String)return a;for(j=0;j<b.length;j+=1)if(b[j]===a)return{$ref:d[j]};b.push(a);d.push(h);if("[object Array]"===Object.prototype.toString.apply(a)){k=[];for(j=0;j<a.length;j+=1)k[j]=f(a[j],h+"["+j+"]")}else for(l in k={},a)Object.prototype.hasOwnProperty.call(a,
l)&&(k[l]=f(a[l],h+"["+JSON.stringify(l)+"]"));return k;case "number":case "string":case "boolean":return a}}(a,"$")});
"function"!==typeof JSON.retrocycle&&(JSON.retrocycle=function(a){var b=/^\$(?:\[(?:\d+|\"(?:[^\\\"\u0000-\u001f]|\\([\\\"\/bfnrt]|u[0-9a-zA-Z]{4}))*\")\])*$/;(function e(a){var g,h,j;if(a&&"object"===typeof a)if("[object Array]"===Object.prototype.toString.apply(a))for(g=0;g<a.length;g+=1){if((h=a[g])&&"object"===typeof h)j=h.$ref,"string"===typeof j&&b.test(j)?a[g]=eval(j):e(h)}else for(g in a)if("object"===typeof a[g]&&(h=a[g]))j=h.$ref,"string"===typeof j&&b.test(j)?a[g]=eval(j):e(h)})(a);return a});var SSP=0,SIM=1,POS=2,EVO=3;onmessage=function(a){var a=JSON.parse(a.data),b=a.G;dist=getDistances(a.A,a.B,b.doEvo,a.gapsHere,b);postMessage(JSON.stringify({type:"success",distances:dist}))};function dssp(a,b,d,e){return d==e&&0<d?[a,b+1]:0<d&&0<e?[a+2,b+2]:0<d||0<e?[a+1,b+1]:[a,b]}function dseq(a,b,d,e){0>d&&(d=0);0>e&&(e=0);return dgen(a,b,d,e)}function dgen(a,b,d,e){return d!=e?[a+1,b+1]:[a,b+1]}var dpos=dgen,devol=dgen;
function quickDistNew(a,b,d){console.log("quickDistNew "+d);var e=[],f=[],g=0,h=0,j,l=2;switch(d){case 0:j=dssp;break;case 1:j=dseq;break;case 2:j=dpos;break;case 3:j=devol,l=3}for(d=0;d<a.length;d++){e[d]=[];for(var k=f[d]=0,p=0,m=0;k<a[d].content.length&&p<b[d].content.length;)if("-"==a[d].content[k])k++;else{if("-"!=b[d].content[p]){for(var q=0,n=0,r=0;r<a.length;r++)r!=d&&(n=j(q,n,a[r].labeledContent[l][k],b[r].labeledContent[l][p]),q=n[0],n=n[1]);f[d]+=q;h+=q;q=0==n?0:q/n;e[d].push(q);m+=n;k++}p++}g+=
m;f[d]/=m}n={};n.character=e;n.alignment=h/g;n.sequence=f;return n}function calcDistances(a,b){console.log("calcDistances");var d=[];console.log("HUH");console.log(a);console.log(a[0].labeledContent);console.log(a[0].labeledContent.length);var e=a[0].labeledContent.length;console.log(e);d.push(_.memoize(function(){return quickDistNew(a,b,0)}));for(var f=1;f<e;f++){var g=_.bind(quickDistNew,{},a,b,f);d.push(_.memoize(g))}return d}
function getIntersection(a,b){for(var d=0,e=0;e<a.length;e++)"-"!=a[e]&&"-"!=b[e]&&a[e]==b[e]&&d++;return d}function getUnion(a,b){for(var d=0,e=0;e<a.length;e++)"-"!=a[e]&&"-"!=b[e]?(d++,a[e]!=b[e]&&d++):("-"!=a[e]||"-"!=b[e])&&d++;return d};SSP=0;SIM=1;POS=2;EVO=3;try{importScripts("newick_parser.js","sequence.js","msgpack.js"),importScripts("http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.3.3/underscore-min.js")}catch(e$$11){}var pack=function(a){return JSON.stringify(a)},unpack=function(a){return JSON.parse(a)};
onmessage=function(a){var a=unpack(a.data),b=a.tree,d=0,e=a.aln;try{e=performHomologyWork(b,e,a.seqNum),e[0].labeledContent[EVO]&&(d=1)}catch(f){f.message?(a=f.stack.replace(/^[^\(]+?[\n$]/gm,"").replace(/^\s+at\s+/gm,"").replace(/^Object.<anonymous>\s*\(/gm,"{anonymous}()@").split("\n"),postMessage(pack({type:"error",msg:f+"\n"+a}))):postMessage(pack({type:"error",msg:f}));return}postMessage(pack({type:"success",ans:e,doEvo:d}))};
function performHomologyWork(a,b,d){if(a){root=parseNewickString(a);treeNames=[];for(a=0;a<root.length;a++)treeNames.push(root[a].name);treeNames.sort();for(a=0;a<b.length;a++)if(treeNames[a]!=b[a].name)throw"Names differ in Newick tree and alignments";if(void 0!=treeNames[b.length])throw"There are more sequences in the Newick tree than in the alignments";doEvo=1;tree=makeTree(root)}else tree=null,doEvo=0;try{postMessage(pack({type:"status",msg:"1"}))}catch(e){}labeller(b,tree,doEvo,d);try{postMessage(pack({type:"status",
msg:"2"}))}catch(f){}return b}function resortNonOverlapping(a,b){var d;do{d=!1;for(var e=0;e<a[0].content.length-1;e++)if(areNonOverlapping(e,a,b)&&shouldBeFlipped(e,a,b)){for(d=0;d<b;d++){var f=a[d].content.substr(0,e).concat(a[d].content[e+1]).concat(a[d].content[e]).concat(a[d].content.substr(e+2));a[d].content=f}d=!0}}while(d);return a}function areNonOverlapping(a,b,d){for(var e=!0,f=0;f<d;f++)if("-"!=b[f][a]&&"-"!=b[f][a+1]){e=!1;break}return e}
function shouldBeFlipped(a,b,d){for(var e=!1,f=0;f<d;f++)if(!("-"==b[f][a]&&"-"==b[f][a+1])){e="-"==b[f][a+1];break}return e};var SSP=0,SIM=1,POS=2,EVO=3,alnBresults=[],alnAresults=[],alnAF,alnBF,padChars=20,charWidth,colDistA,colDistB,sparkLineClickA,sparkLineClickB,homType=2,sparklineDistanceType=!0,G={},pack=function(a){return JSON.stringify(a)},unpack=function(a){return JSON.parse(a)},alertFallback=!1;if("undefined"===typeof console||"undefined"===typeof console.log)console={},console.log=alertFallback?function(a){alert(a)}:function(){};
$(function(){draganddrop("#alignment1");draganddrop("#alignment2");draganddrop("#newick");$("#alignment2File").bind("change",getHandleFileSelect($("#alignment2")));$("#alignment1File").bind("change",getHandleFileSelect($("#alignment1")));$("#newickFile").bind("change",getHandleFileSelect($("#newick")))});function getHandleFileSelect(a){return function(b){var b=b.originalEvent||b,d=b.target.files[0];console.log(b);getFile(d,a)}}
function getFile(a,b){console.log("Attempting to get "+a);var d=new FileReader;d.onload=function(a){console.log(a);b.val(a.target.result)};d.readAsText(a)}function draganddrop(a){var b=$(a);b.bind({dragover:function(){$(this).addClass("hover");return!1},dragend:function(){$(this).removeClass("hover");return!1},drop:function(a){a=a||window.event;a.preventDefault();a=a.originalEvent||a;console.log(a);getFile((a.files||a.dataTransfer.files)[0],b);return!1}})}
function example(a){$.ajax(location.protocol+"//"+location.host+"/"+location.pathname.split("/").slice(0,-1).join("/")+"/examples/example"+a+"a.fa").done(function(a){$("#alignment1").val(a)});$.ajax(location.protocol+"//"+location.host+"/"+location.pathname.split("/").slice(0,-1).join("/")+"/examples/example"+a+"b.fa").done(function(a){$("#alignment2").val(a)});$.ajax(location.protocol+"//"+location.host+"/"+location.pathname.split("/").slice(0,-1).join("/")+"/examples/example"+a+".tre").done(function(a){$("#newick").val(a)})}
function supports_web_workers(){return!!window.Worker}var useWorkers=supports_web_workers(),START=new Date;function dateStamp(a){var b=new Date;console.log(b-START+" : "+a);START=b}function process(){$("#errorBox").css("display","none");$("#dialogtext").html("Calculation of homology sets");dialogBox.center();dialogBox.open();dateStamp("end process()");_.defer(process1)}
function process1(){console.log("process1");G.doEvo=0;try{alnA=parser($("#alignment1").val(),"alignment 1");alnB=parser($("#alignment2").val(),"alignment 2");"nucleotide"==G.sequenceType&&$("#distanceVisualizationType").html($("#nuc-distanceVisualizationType").html());$("#nuc-distanceVisualizationType").remove();$("#distanceVisualizationType").kendoDropDownList({autoBind:!0});$("#distanceVisualizationType").data("kendoDropDownList").toggle();$("#distanceVisualizationType").data("kendoDropDownList").toggle();
alnA.sort(nameSorter);alnB.sort(nameSorter);alnADensity=calcDensity(alnA);alnBDensity=calcDensity(alnB);var a=checkConsistency(alnA,alnB);G.sequenceNumber=a[0];G.origLengths=a[1];G.names=nameLookup(alnA,G.sequenceNumber);newick_string=$("#newick").val().replace(/\s/g,"");dateStamp("")}catch(b){$("#errorBox").html("<b>ERROR: "+b+"</b>");$("#errorBox").fadeIn();dialogBox.close();return}alnAresults=[];alnBresults=[];alnAresults[0]=[];alnBresults[0]=[];var d=_.after(2,process2);_.defer(function(){doHomology(newick_string,
alnA,G.sequenceNumber,d)});_.defer(function(){doHomology(newick_string,alnB,G.sequenceNumber,d)});dateStamp("end process1()")}
function doHomology(a,b,d,e){if(useWorkers){var f=new Worker("script/homologySets.js");f.onmessage=function(a){a=unpack(a.data);if("error"==a.type)throw"ERROR: "+a.msg;"status"==a.type?dateStamp(a.msg):"success"==a.type&&(dateStamp("Got MSG"),alnA===b?(alnA=a.ans,G.doEvo=a.doEvo,console.log("doEvo? "+a.doEvo),homType=2+G.doEvo):alnB===b&&(alnB=a.ans),e())};f.postMessage(pack({tree:a,aln:b,seqNum:d,set:3}));dateStamp("Sent MSG")}else performHomologyWork(a,b,d,3),b[0].labeledContent[EVO]&&(G.doEvo=
1,homType=3),e()}function process2(){_.defer(function(){$("#dialogtext").html("Calculation of distances")});console.log("PROCESS 2");distanceFs=calcDistances(alnA,alnB);console.log(distanceFs.length);distances={character:[],alignment:[],sequence:[]};_.defer(process3);dateStamp("end process2()")}
function updateCurrentHomType(){console.log(distanceFs);console.log(distanceFs.length);console.log("UPDATE HOM");var a=distanceFs[homType]();distances.character[homType]=a.character;distances.alignment[homType]=a.alignment;distances.sequence[homType]=a.sequence}function process3(){G.visualize=$("#doviz:checked").val();$("#controlPanel").css("display","");$("#input").remove();$("#instructions").remove();_.defer(updateCurrentHomType);_.defer(vis);dateStamp("end process3()")}
function vis(){console.log("VIS");if(G.visualize){G.doEvo?($("#evol").removeAttr("disabled"),$("#evol").html("evol (recommended)"),$("#pos").html("pos"),$("#homologyType").val(homType)):$("#evol").remove();$("#homologyType").kendoDropDownList({autoBind:!0});$("#homologyType").data("kendoDropDownList").toggle();$("#homologyType").data("kendoDropDownList").toggle();$("#distanceVisualizationPanel").css("display","inline");cssCache=[[],[],[],[]];var a=colouredSequenceMaker(distanceFs,alnA,"alnA"),b=colouredSequenceMaker(distanceFs,
alnB,"alnB");alnAF=a;alnBF=b;a=alnAF[0];b=alnBF[0];parseInt($("#distanceVisualizationType option:selected").val());a=makeVisualiser(a,b,alnA,alnB);$("body").append(a);$("#distanceToggle").click(function(){console.log("CLICK");(sparklineDistanceType=!sparklineDistanceType)?$(this).html("similarity"):$(this).html("distance");doRedisplaySparklines()});sparklineDistanceType?$("#distanceToggle").html("similarity"):$("#distanceToggle").html("distance");applyCSS(alnAF[0],alnAF[1][homType]());applyCSS(alnBF[0],
alnBF[1][homType]());a=$("#alnA_seqs").outerWidth();charWidth=getCharWidth();for(var b=charPadding(padChars),d=0;d<G.sequenceNumber;d++)$(".seq_"+d).prepend(b),$(".seq_"+d).append(b);a=parseInt(0.5*a/charWidth)*charWidth;$("#alnA_seqs").scrollLeft(a);$("#alnB_seqs").scrollLeft(a);var e,f,g,h,a=getPositions(alnA),b=getPositions(alnB);e=a[0];f=a[1];g=b[0];h=b[1];var j="",l=0,k=l,p=cumulativeGaps(alnA),m=cumulativeGaps(alnB),q=function(){$("#alnA_seqs").scrollLeft(e[l][central]*charWidth);$("#alnB_seqs").scrollLeft(g[l][central]*
charWidth);redisplaySparklines()};sparkLineClickA=function(a){console.log("GOT CLICK");console.log(a.sparklines);console.log(a.sparklines[0].getCurrentRegionFields());central=a.sparklines[0].getCurrentRegionFields().offset;central-=p[l][central];n();q()};sparkLineClickB=function(a){central=a.sparklines[0].getCurrentRegionFields().offset;central-=m[l][central];n();q()};recalculateSparklines();redisplaySparklines();recalculateMinilines();$("#alnB_sparkline").bind("sparklineClick",sparkLineClickB);$("#alnA_sparkline").bind("sparklineClick",
sparkLineClickA);var n=function(){$("#alnA_"+k+"_"+j).removeClass("centralChar");$("#alnB_"+k+"_"+j).removeClass("centralChar");k=l;j=central;$("#charDist").text(Math.round(1E3*distances.character[homType][l][central])/1E3);$("#alnA_"+l+"_"+central).addClass("centralChar");$("#alnB_"+l+"_"+central).addClass("centralChar")};$("#alnA_seqs").bind("click",function(a){l=$(a.target).closest("div").index();central=f[l][$(a.target).closest("span").index()-padChars];n()});$("#alnB_seqs").bind("click",function(a){l=
$(a.target).closest("div").index();central=h[l][$(a.target).closest("span").index()-padChars];n()});scrollA=_.debounce(function(){visibleRange($("#alnA_seqs"),alnA[0].content.length);central=f[l][Math.round($("#alnA_seqs").scrollLeft()/charWidth)];n();$("#alnB_seqs").off("scroll");$("#alnB_seqs").scrollLeft(g[l][central]*charWidth);$("#alnB_seqs").scrollTop($("#alnA_seqs").scrollTop());$("#alnA_names").scrollTop($("#alnA_seqs").scrollTop());$("#alnB_names").scrollTop($("#alnA_seqs").scrollTop());
redisplaySparklines();_.defer(function(){$("#alnB_seqs").on("scroll",scrollB)})},200);scrollB=_.debounce(function(){central=h[l][Math.round($("#alnB_seqs").scrollLeft()/charWidth)];n();$("#alnA_seqs").off("scroll");$("#alnA_seqs").scrollLeft(e[l][central]*charWidth);$("#alnA_seqs").scrollTop($("#alnB_seqs").scrollTop());$("#alnA_names").scrollTop($("#alnB_seqs").scrollTop());$("#alnB_names").scrollTop($("#alnB_seqs").scrollTop());redisplaySparklines();_.defer(function(){$("#alnA_seqs").on("scroll",
scrollA)})},200);$("#alnA_seqs").on("scroll",scrollA);$("#alnB_seqs").on("scroll",scrollB);a=function(){$("#distanceVisualizationType option:selected").each(function(){var a=$(this).val();$("#seqColour").attr("href","css/"+a+".css")})};a();$("#distanceVisualizationType").change(a)}_.defer(function(){dialogBox.close()});_.defer(bindings);dateStamp("end vis()")}
function bindings(){$("#homologyType").change(function(){homType=parseInt($(this).val());updateCurrentHomType();var a=Math.round(1E6*distances.alignment[homType])/1E6;$("#alnDist").text(a);parseInt($("#distanceVisualizationType option:selected").val());G.visualize&&(applyCSS(alnAF[0],alnAF[1][homType]()),applyCSS(alnBF[0],alnBF[1][homType]()),recalculateSparklines(),redisplaySparklines(),recalculateMinilines());G.charDists&&(a=makeCharDist(distances,homType,alnA),$("#chardists").replaceWith(a))});
var a=makeOutput(distances,homType,alnA);$("body").append(a[0]);$("#showCharDists").click(function(){var a=window.open("","charDists","height=400,width=400");a.document.write("<html><head>");a.document.write("</head><body><pre>");a.document.write(makeRawCharDist(distances,homType,alnA).join("\n"));a.document.write("</pre></body></html>");a.document.close()});$("#showSeqDists").click(function(){var a=window.open("","seqdists","height=600,width=400"),d=makeOutput(distances,homType,alnA);a.document.write("<html><head></head><body>"+
$("<div/>").append(d[1]).html()+"</body></html>");a.document.close()});a=function(){var a=$(window).height(),d=$("#visualiser").offset().top,d=d+$("#visualiser").outerHeight(!0),d=d-$("#alnA_seqs").outerHeight(!0),d=d-$("#alnB_seqs").outerHeight(!0),d=d+$("#output table").outerHeight(!0),a=(a-d)/2;$("#alnA_seqs").css("height",a);$("#alnA_names").css("height",a);$("#alnB_seqs").css("height",a);$("#alnB_names").css("height",a);redisplaySparklines()};a();$(window).resize(a);$("#consensus").on("click",
function(){var a=window.open("","consensus","height=400,width=400");a.document.write("<html><head>");a.document.write("</head><body><pre>");for(var d=0;d<alnA.length;d++){a.document.write(">"+alnA[d].name+"\n");for(var e=[],f=0;f<alnA[d].content.length;f++)0==colDistA[f]&&e.push(alnA[d].content[f]);a.document.write(e.join("")+"\n")}a.document.write("</pre></body></html>")});dateStamp("end bindings()")}
function cumulativeGaps(a){for(var b=[],d=0;d<a.length;d++){b[d]=[];b[d][0]="-"==a[d].content[0]?1:0;for(var e=1;e<a[d].content.length;e++)b[d][e]="-"==a[d].content[e]?b[d][e-1]+1:b[d][e-1]}return b}function recalculateSparklines(){colDistA=makeRawColumnDist(distances,homType,alnA);colDistB=makeRawColumnDist(distances,homType,alnB);redisplaySparklines=_.throttle(doRedisplaySparklines,1E3)}
function doRedisplaySparklines(){console.log("distance "+sparklineDistanceType);applyColumnDist(colDistA,alnADensity,$("#alnA_seqs"),$("#alnA_sparkline"),$("#alnA_seqs").width(),sparklineDistanceType);applyColumnDist(colDistB,alnBDensity,$("#alnB_seqs"),$("#alnB_sparkline"),$("#alnB_seqs").width(),sparklineDistanceType)}
function recalculateMinilines(){for(var a=new Date,b=0;b<distances.sequence[homType].length;b++){var d=$(".miniline_"+b);d.css("width","30%");d.html("<img src='png/"+Math.floor(100*distances.sequence[homType][b])+".png' title='"+distances.sequence[homType][b]+"' height='10px' style='max-width:100%'/>")}console.log(new Date-a)}
function calcDensity(a){for(var b=[],d=0;d<a.length;d++)for(var e=0;e<a[d].content.length;e++)"-"!=a[d].content[e]&&(b[e]||(b[e]=0),b[e]++);for(d=0;d<b.length;d++)b[d]/=a.length;return b};try{importScripts("http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.3.3/underscore-min.js")}catch(e$$20){}function Node(){if(!(this instanceof Node))return new Node}Node.prototype.isRoot=function(){return"undefined"===typeof this.nodeparent};Node.prototype.isLeaf=function(){return"undefined"===typeof this.children||0==this.children.length};
Node.prototype.descendents=function(){try{var a;a=nodeList(this);var b=[];for(i=0;i<a.length;i++)a[i].isLeaf()&&b.push(a[i].name);return b}catch(d){throw"WTF!";}};Node.prototype.allSplits=function(){var a=this.descendents().sort(),b;b=nodeList(this);for(var d=[],e=0;e<b.length;e++)if(b[e].isLeaf())d.push([[b[e].name],_.without(a,b[e].name).sort()]);else{var f=b[e].descendents().sort();d.push([f,_.difference(a,f).sort()])}return d.sort()};
Node.prototype.splitsIDs=_.memoize(function(){var a=this.allSplits(),b={},d=0;_.each(a,function(a){b[a[0]]=d;b[a[1]]=d;d++});return b});Node.prototype.splitsFor=function(a){var b=this.splitsIDs();if(this.isRoot()){var d=splitsForRoot(this,a);_.chain(d).keys().each(function(a){d[a]=b[d[a].sort()]});return d}throw Error("Only call Node#splitsFor on the root!");};var c=0;
Node.prototype.findNodeWithNoneDesc=function(a){if(_.difference(this.descendents(),a).length==this.descendents().length)return this;if(this.children)for(var b=0;b<this.children.length;b++){var d=this.children[b].findNodeWithNoneDesc(a);if(d)return d}return null};
Node.prototype.downCopy=function(a){var b=nodeList(this),d=[];_.each(b,function(a){var b=new Node;a.name&&(b.name=a.name);b.id=a.id;d[b.id]=b});_.each(b,function(a){var b=d[a.id];a.nodeparent&&(b.nodeparent=d[a.nodeparent.id]);a.children&&(b.children=[],_.each(a.children,function(a){b.children.push(d[a.id])}))});d[this.id].nodeparent=a;a.children.push(d[this.id])};c=0;
Node.prototype.upCopy=function(a,b){var d=new Node;d.name=this.name;d.id=this.id;d.children=[];d.nodeparent=a;a.children.push(d);_.chain(this.children).filter(function(a){return a!==b}).each(function(a){a.downCopy(d)});this.nodeparent&&this.nodeparent.upCopy(d,this)};
Node.prototype.rootedCopy=function(){var a=new Node;a.name=this.nodeparent.name;a.id=this.nodeparent.id;a.children=[];_.each(this.nodeparent.children,function(b){b.downCopy(a)});this.nodeparent.nodeparent&&this.nodeparent.nodeparent.upCopy(a,this.nodeparent);return a};c=0;function splitsForRoot(a,b){var d=splitsForX(a,b);return _.reduce(d,function(a,b){a[b[0]]=b[1];return a},{})}
function splitsForX(a,b){var a=a.findNodeWithNoneDesc(b).rootedCopy(),d={},e={},f={},g=nodeList(a).reverse();_.each(g,function(a){var b;b=a.descendents();try{f[a.id]=b}catch(d){throw b;}});_.each(b,function(a){e[a]=1});for(var h=0;h<g.length;h++){var j=g[h];if(!j.children||0==j.children.length)1==e[j.name]&&(d[j.id]=1);else{var l=!0;_.each(j.children,function(a){d[a.id]||(l=!1)});l&&(_.each(j.children,function(a){delete d[a.id]}),d[j.id]=1)}}var k=[],p=_.filter(g,function(a){return d[a.id]}),m=!1;
_.each(p,function(b){var d=f[b.id];if(b.nodeparent===a){if(!m){m=!0;for(firstLevel=_.chain(p).filter(function(d){return d.nodeparent===a&&b!==d}).value();0<firstLevel.length;)d=d.concat(f[firstLevel.pop().id]);_.each(d,function(a){k.push([a,d])})}}else _.each(d,function(a){k.push([a,d])})});return k}Array.prototype.difference=function(a){return this.filter(function(b){return-1<a.indexOf(b)})};
Node.prototype.toString=function(){return this.children?(childstr="("+this.children.map(function(a){return a.toString()}).join()+")",this.isRoot()?childstr+";":childstr):this.name};
function parseNewickString(a){a=a.replace(/:[^),;]*/g,"");a=a.replace(/\)[^),;]*/g,")");if("("!=a[0])throw'Error: newick trees must start with an opening nodeparenthesis: "("';if(";"!=a[a.length-1])throw'Error: newick trees must end with a semi-colon: ";"';for(var b=unmatched=0;b<a.length;b++)"("==a[b]&&unmatched++,")"==a[b]&&unmatched--;if(0!=unmatched)throw"Error: newick tree contains different number of opening and closing nodeparentheses. ";temp={index:0,cursor:0,nodeparents:[]};a=basicParse(a);
delete temp;return a}function basicParse(a){if(null==b)var b=[];for(;";"!=a[temp.cursor];)switch(a[temp.cursor]){case "(":temp.cursor++;newNode(null,b,a);break;case ",":temp.cursor++;break;case ")":temp.nodeparents.pop();temp.cursor++;break;case ";":break;default:var d=a.substring(temp.cursor).match("^[0-9A-Za-z_|/\\.-]+"),d=d instanceof Array?d[0]:d;temp.cursor+=d.length;newNode(d,b,a)}return b}
function newNode(a,b,d){b[temp.index]=new Node;null==a?(b[temp.index].children=[],nodeLinker(b,d),temp.nodeparents.push(temp.index)):(b[temp.index].name=a,nodeLinker(b,d));temp.index++}function nodeLinker(a){temp.nodeparents.length&&(a[temp.index].nodeparent=temp.nodeparents[temp.nodeparents.length-1],a[a[temp.index].nodeparent].children.push(temp.index))}
function fixNode(a,b){b.children&&(b.children=b.children.map(function(b){return a[b]}));if(b.nodeparent||0==b.nodeparent)b.nodeparent=a[b.nodeparent];return b}function getRoot(a){for(var b=0;b<a.length;b++){var d=a[b];if(d.isRoot())return d}}function nodeList(a){var b=[];b.push(a);for(a=0;a<b.length;){if(b[a].children)for(var d=b[a].children,e=0;e<d.length;e++)b.push(d[e]);a+=1}return b}function enforceBi(a){stack=nodeList(a)[0];for(a=stack.length-1;0<=a;a--)doEnforceBi(stack[a])}
function doEnforceBi(a){if(a.children&&2!=a.children.length&&!(3==a.children.length&&a.isRoot()))if(1==a.children.length){par=a.nodeparent;a.children[0].nodeparent=par;for(var b=0;b<par.children.length;b++)par.children[b]==this&&(par.children[b]=a.children[0])}else for(;2<a.children.length;)b=new Node,b.children=a.children.slice(0,2),b.nodeparent=a,a.children[1]=b,a.children.shift()}
function unroot(a){if(3==a.children.length)return a;if(2!=a.children.length)throw Error("Tree is neither already rooted or bifurcating");a.children[0].isLeaf?(newroot=a.children[1],newchild=a.children[0]):(newroot=a.children[0],newchild=a.children[1]);newroot.children.push(newchild);newchild.nodeparent=newroot;newroot.nodeparent=void 0;return newroot}function makeTree(a){var b=getRoot(a.map(function(b){return fixNode(a,b)}));enforceBi(b);b=unroot(b);return numberNodes(b)}
function numberNodes(a){stack=nodeList(a);var b=0;_.each(stack,function(a){a.id=b;b++});return a};importScripts("newick_parser.js","cycle.js","//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.3.3/underscore-min.js");
onmessage=function(a){var b=JSON.parse(a.data),a=b.tree,b=b.aln;try{if(a){root=parseNewickString(a);treeNames=[];for(a=0;a<root.length;a++)treeNames.push(root[a].name);treeNames.sort();for(a=0;a<b.length;a++)if(treeNames[a]!=b[a].name)throw"Names differ in Newick tree and alignments";if(void 0!=treeNames[b.length])throw"There are more sequences in the Newick tree than in the alignments";tree=makeTree(root);postMessage(JSON.stringify({type:"success",tree:JSON.decycle(tree)}))}}catch(d){d.message?(a=
d.stack.replace(/^[^\(]+?[\n$]/gm,"").replace(/^\s+at\s+/gm,"").replace(/^Object.<anonymous>\s*\(/gm,"{anonymous}()@").split("\n"),postMessage(JSON.stringify({type:"error",msg:d+"\n"+a}))):postMessage(JSON.stringify({type:"error",msg:d}))}};function sequenceMaker(a,b){$sequenceDiv=$("<div/>").attr("id",b+"_seqs").addClass("seqs");for(var d=0;d<G.sequenceNumber;d++){$colouredSeqDivs=$("<div/>").addClass("seq_"+d);for(var e=0,f=0;f<a[d].content.length;f++){var g=$("<span/>").text(a[d].content[f]).addClass(a[d].content[f].toUpperCase()).addClass("clickable");"-"!=a[d].content[f]&&(g.attr("id",b+"_"+d+"_"+e),e++);$colouredSeqDivs.append(g)}$sequenceDiv.append($colouredSeqDivs)}return $sequenceDiv}
function colouredCSSMaker(a,b){for(var d=[],e=0;e<a.length;e++)d[e]=_.memoize(_.bind(function(d){for(var d=a[d]().character,e=[],h=[],j=0;j<G.sequenceNumber;j++){h[j]=[];for(var l=0,k=0;k<b[j].content.length;k++)"-"!=b[j].content[k]?($character=[Math.round(255*d[j][l]),Math.round(1E6*d[j][l])/1E6],l++):$character=null,h[j].push($character);e.push(h[j])}return e},{},e));return d}
function applyCSS(a,b){var d=0;_.each($(a).children("div"),function(a){var f=0;_.each($(a).contents(".clickable"),function(a){if(b[d][f]){var e=$(a);_.chain(e.attr("class").split(" ")).filter(function(a){return"dist"==a.substring(0,4)}).each(function(a){e.removeClass(a)});e.addClass("dist"+b[d][f][0]);e.attr("title",b[d][f][1])}f++});d++});return a}function colouredSequenceMaker(a,b,d){var e=sequenceMaker(b,d),a=colouredCSSMaker(a,b,d);return[e,a]}
function makeVisualiser(a,b,d,e){var f=$("<div/>").attr("id","visualiser"),g=$("<div/>").attr("id","alnA_names").addClass("names"),h=$("<div/>").attr("id","alnB_names").addClass("names");for(i=0;i<G.sequenceNumber;i++)0==i%2?(g.append("<div class='row0'><div class='name' title='"+d[i].name+"'>"+d[i].name+"</div><div class='miniline_"+i+"'></div></div>"),h.append("<div class='row0'><div class='name' title='"+e[i].name+"'>"+e[i].name+"</div><div class='miniline_"+i+"'></div></div>")):(g.append("<div class='row1'><div class='name' title='"+
d[i].name+"'>"+d[i].name+"</div><div class='miniline_"+i+"'></div></div>"),h.append("<div class='row1'><div class='name' title='"+e[i].name+"'>"+e[i].name+"</div><div class='miniline_"+i+"'></div></div>"));g.append($("<div>&nbsp;</div>").css("height",scrollbarWidth()));h.append($("<div>&nbsp;</div>").css("height",scrollbarWidth()));d=$("<div/>").append(g,a).attr("id","alnA_scroll").addClass("scrollbox");b=$("<div/>").append(h,b).attr("id","alnB_scroll").addClass("scrollbox");h=$("<button class='k-button' id='distanceToggle' />");
h.css("height","30px").css("font-size","14px").css("margin-top","7px");e=$("<span />").attr("id","alnA_sparkline").css("height","40px").css("width",a.width()).css("float","right").css("padding-top","5px");e=$("<div />").css("width","100%").css("overflow","hidden").css("display","block").append(h).append(e);h.html("distance");a=$("<span />").attr("id","alnB_sparkline").css("height","40px").css("width",a.width()).css("float","right").css("padding-top","5px");a=$("<div />").css("width","100%").css("overflow",
"hidden").css("display","block").append(a);f.append(d,e,b,a);return f}
function makeOutput(a,b,d){var e=$("<div/>").attr("id","output"),f=$("<table/>").attr("id","output"),g=Math.round(1E6*a.alignment[b])/1E6;if(G.visualize){var h=$("<table/>").css("display","inline").css("float","left").append($("<tr />"));h.append($("<td />").append("Total alignment distance:"));h.append($("<td />").attr("id","alnDist").css("width","8em").css("font-weight","bold").text(g));e.append(h);h=$("<table/>").css("display","inline").css("float","right").append($("<tr />"));h.append($("<td />").append("Focused character distance:"));
h.append($("<td />").attr("id","charDist").css("font-weight","bold").css("width","5em"));e.append(h)}var h=$("<tr/>"),g=$("<td />").attr("id","alnDist").text(g),j=$("<td />").append("Alignment distance");h.append(j);h.append(g);for(g=0;g<G.sequenceNumber;g++){var l=Math.round(1E6*a.sequence[b][g])/1E6,j=$("<tr/>"),k=$("<td/>").append("Distance for sequence "+d[g].name),l=$("<td/>").attr("id",d[g].name+"_dist").text(l);j.append(k);j.append(l);f.append(j)}f.append(h);return[e,f]}
function makeCharDist(a,b,d){for(var e=$("<div/>").attr("id","chardists"),f=[],g=0;g<G.sequenceNumber;g++){var h=[];h.push(d[g].name);for(var j=0;j<G.origLengths[g];j++)h.push(a.character[b][g][j]);f[g]=$("<p/>").attr("id","chardists_"+d[g].name).html(h.toString());e.append(f[g])}return e}function makeRawCharDist(a,b,d){for(var e=[],f=0;f<G.sequenceNumber;f++){var g=[];g.push(d[f].name);for(var h=0;h<G.origLengths[f];h++)g.push(a.character[b][f][h]);e.push(g)}return e}
function makeRawColumnDist(a,b,d){for(var e=[],f=0;f<d[0].content.length;f++)e[f]=0;for(var g=0;g<d.length;g++)for(var h=0,j=d[g].content,f=0;f<j.length;f++)"-"!=j[f]&&(e[f]+=a.character[b][g][h]/d.length,h++);return e}function makeVisualColumnDist(a,b,d,e,f,g){a=makeRawColumnDist(a,b,d);applyColumnDist(a,e,f,g)}
function visibleRange(a,b){var d=a.scrollLeft(),e=a[0].scrollWidth,f=a.width(),g=b+2*padChars,h=Math.floor(d/e*g),h=h-padChars,d=Math.floor((d+f)/e*g),d=d-padChars;d>b&&(d=b);0>h&&(h=0);return[h,Math.floor((h+d)/2),d]}
function applyColumnDist(a,b,d,e,f,g){for(var h=visibleRange(d,a.length),d=h[0],h=h[2],j=[],l=[],k=[],p=[],m=0;m<d;m++)j.push(a[m]),l.push(null),k.push(b[m]),p.push(null);j.push(a[d]);l.push(a[d]);k.push(b[d]);p.push(b[d]);for(m=d+1;m<h-1;m++)l.push(a[m]),j.push(null),p.push(b[m]),k.push(null);j.push(a[h-1]);l.push(a[h-1]);p.push(b[h-1]);k.push(b[h-1]);for(m=h;m<a.length;m++)j.push(a[m]),l.push(null),k.push(b[m]),p.push(null);e.css("width",f+"px");barWidth=Math.max(f/a.length,1);console.log("INVERT? "+
g);if(g)for(m=0;m<a.length;m++)null!=j[m]&&(j[m]=b[m]-j[m]),null!=l[m]&&(l[m]=b[m]-l[m]);e.sparkline(k,{width:f,chartRangeMax:1,chartRangeMin:0,height:"30px",lineColor:"#444444",fillColor:"#444444",disableTooltips:!0,disableHighlight:!0,spotColor:!1,minSpotColor:!1,maxSpotColor:!1});e.sparkline(p,{composite:!0,width:f,chartRangeMax:1,chartRangeMin:0,height:"30px",lineColor:"black",fillColor:"black",disableTooltips:!0,disableHighlight:!0,spotColor:!1,minSpotColor:!1,maxSpotColor:!1});e.sparkline(j,
{composite:!0,chartRangeMax:1,chartRangeMin:0,height:"30px",chartRangeMax:1,width:f,fillColor:"#6c8be9",lineColor:!1,disableTooltips:!0,disableHighlight:!0,spotColor:!1,minSpotColor:!1,maxSpotColor:!1});e.sparkline(l,{width:f,chartRangeMax:1,chartRangeMin:0,height:"30px",composite:!0,lineColor:!1,fillColor:"blue",disableTooltips:!0,disableHighlight:!0,spotColor:!1,minSpotColor:!1,maxSpotColor:!1})}$(window).resize(function(){divWidth=$("#alnA_Seqs").width()});
function getPositions(a){for(var b=[],d=[],e=0;e<G.sequenceNumber;e++){b[e]=[];d[e]=[];for(var f=0,g=0;g<a[e].content.length;g++)d[e][g]=f,b[e][f]=g,"-"!=a[e].content[g]&&f++}return[b,d]}function scanCentralChar(a){for(startingPoint=Math.round(a);void 0==characterAt[0][0][startingPoint];)startingPoint--;return characterAt[0][0][startingPoint]}
function charPadding(a){str='<span class="padding">&nbsp;</span>';if(!a)return"";for(var b=str,d=[str],e=1,f,g;e<a;){f=a-e;str=b;for(g=2;g<f;g*=2)str+=str;d.push(str);e+=g/2}return d.join("")}
function transparentAminoCSS(a,b){for(var d=[],e=0;e<G.sequenceNumber;e++){d[e]=[];console.log("transparentAminoCSS "+b);for(var f=0;f<G.origLengths[e];f++)opacity=1==b?a[e][f]:2==b?1:1-a[e][f],console.log($("#alnA_"+e+"_"+f).css("background-color")),d[e].push($("#alnA_"+e+"_"+f).css("background-color").replace("rgb","rgba").replace(")",", "+opacity+")")),console.log(d[e][f])}return d}
function changeDistanceVisualization(a){if(a)for(b=0;b<G.sequenceNumber;b++)for(d=0;d<G.origLengths[b];d++)$("#alnA_"+b+"_"+d).css("background-color",a[b][d]),$("#alnB_"+b+"_"+d).css("background-color",a[b][d]);else for(var b=0;b<G.sequenceNumber;b++)for(var d=0;d<G.origLengths[b];d++)$("#alnA_"+b+"_"+d).css("background-color","")}
function getCharWidth(){var a,b=$("<div/>").addClass("seqs");b.append($("<span id='widthTest'>A</span>"));b.appendTo($("body"));a=parseInt($("#widthTest").css("padding-left"))+parseInt($("#widthTest").css("padding-right"))+$("#widthTest").width();b.remove();return a-1}
function scrollbarWidth(){var a=jQuery('<div style="width: 100%; height:200px;">test</div>'),b=jQuery('<div style="width:200px;height:150px; position: absolute; top: 0; left: 0; visibility: hidden; overflow:hidden;"></div>').append(a),d=a[0],a=b[0];jQuery("body").append(a);d=d.offsetWidth;b.css("overflow","scroll");a=a.clientWidth;b.remove();return d-a};function Sequence(a,b){if(!(this instanceof Sequence))return new Sequence(a,b);this.name=a;this.content=b}var nextNodeID=0,nodeIDs={};function nodeID(a){return a.toString()+"---"}
function parser(a,b){var d=[],e,f,g=RegExp("(^>.+)(?:\n)(^[^>]+)","mg");G.sequenceType="nucleotide";for(var h=/[^ABCDEFGHIKLMNOPQRSTUVWYZXabcdefghiklmnopqrstuvwyzx*-]/,j=/[EFILOPQZefilopqz*]/,l,k=0;parsing=g.exec(a);){e=parsing[1].trim().replace(/^>/,"").replace(/\s/g,"_");f=parsing[2].trim().replace(/\n/g,"");var p=f.search(h);if(-1!=p)throw"Invalid character in sequence "+e+': "'+f[p]+'"';-1!=f.search(j)&&(G.sequenceType="amino acid");d[k]=new Sequence(e,f);if(l&&l!=d[k].content.length)throw"Sequences of differing lengths in "+
b;l=d[k].content.length;k++}return d}function labeller(a,b,d,e){for(var f=0;f<e;f++)a[f].labeledContent=[];d&&evoLabeller(a,b,e);for(f=0;f<e;f++){a[f].labeledContent[SSP]=[];a[f].labeledContent[SIM]=[];a[f].labeledContent[POS]=[];for(var g=b=0,h=0;h<a[f].content.length;h++)"-"!=a[f].content[h]?(g=++b,a[f].labeledContent[POS].push(g),d&&(a[f].labeledContent[EVO][h]=g)):(a[f].labeledContent[POS].push(-g),d&&(a[f].labeledContent[EVO][h]=-(1E4*a[f].labeledContent[EVO][h]+g)))}}
function nameLookup(a,b){names={};for(var d=0;d<b;d++)names[a[d].name]=d;return names}function evoLabeller(a,b,d){for(var e=nameLookup(a,d),f=0;f<d;f++)a[f].labeledContent[EVO]=[];for(var g=0;g<a[0].content.length;g++){gapMemory=[];for(f=0;f<d;f++)"-"==a[f].content[g]&&gapMemory.push(a[f].name);if(0<gapMemory.length){splits=b.splitsFor(gapMemory);for(f=0;f<gapMemory.length;f++)a[e[gapMemory[f]]].labeledContent[EVO][g]=splits[gapMemory[f]]}}}
function nameSorter(a,b){return void 0==a.name&&void 0!=b.name?1:void 0==b.name&&void 0!=a.name||a.name<b.name?-1:a.name>b.name?1:0};
